{%set name = "sphinx-argparse" %}
{%set version = "0.1.17" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a237343dd2c0f27b1a21b9bbd84906a74292f616a81e0e93d8762e1355b47405" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - sphinx

  run:
    - python
    - sphinx

test:
  imports:
    - sphinxarg

about:
  home: https://github.com/ribozz/sphinx-argparse
  license: MIT
  summary: 'Sphinx extension that automatically document argparse commands and options'

extra:
  recipe-maintainers:
    - pmlandwehr
    - croth1
