{% set name = "sphinx-argparse" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82151cbd43ccec94a1530155f4ad34f251aaca6a0ffd5516d7fadf952d32dc1e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python =2.7|>=3.6
    - poetry-core
    - setuptools
  run:
    - python =2.7|>=3.6
    - commonmark >=0.5.6
    - sphinx

test:
  imports:
    - sphinxarg

about:
  home: https://github.com/alex-rudakov/sphinx-argparse
  license: MIT
  license_file: LICENSE
  summary: Sphinx extension that automatically documents argparse commands and options

extra:
  recipe-maintainers:
    - croth1
    - dpryan79
