travis:
  secure:
    BINSTAR_TOKEN: sr+OAkmpSltTnjSgijpH2KA5HZqrzovc5SwsAuyIKBz8g63wHjwxPW7HY8uq1nDW+PQHobvfhiUCca7qwI0ycvFxTjOX3HOWcb0rKOU0/Tc30fohS1unVFxQV1j+O0GmP5vm3PSYIxW4/ij87kQ/cbttcfNL1CTVsjg1DHQ9mo/iZ2RkcmkkPSDVdDz4Tm93hYpLmpA3XbsMrH6131dGWc0l6S57J+8rWQm7rUg8wo6L9KtmnMSqwzvGRVXmSAVoRslz2BMfTgFeH2bLNHcMYScvPDEjETrrz19dKTW9Va6bOaqSW0nN00bOyBVlytxfNwk5zfKtj+gzFnYcdEY41OTABBETe/a7ZKjbAtbdSo8Mvozeuk55amPPrciHF1ftZdMRClUgiTo89aYkEcZ4PibpBeTh7kxVGIrIWay/aMcQsjwpiKPSO0ktpKXBeNSwhm+vvO66H2C/AQJT7MSuDQINxapu1EbxXTPNfxRl4BZxh4k840Xt/1/ScgzWp43f4nWPa5xXVF9rvXKXQH2ZiP+B8DiqXPXozUwdiofR41BgXh6/tsyC6LMZuAa4XmmNfZlM1GM61gTFyIXgFdehvIi3UdhDAoq2+vB/zglpccwtXhdGxC7WLCczF9QZsgArHvIeDsROx9zXgnhWAByOuVK6T9rxnW7RsVgiXl1HCZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
