travis:
  secure:
    BINSTAR_TOKEN: Gm/s7/mkeAkipmUaK8jv3X7XeAptN8jP+1WJcHDNmBn1kSznLyfil2FsR5wVJEiTmSqDhMfPC0gw7gNkt1Sqf4ME+FYKNHbAY+LJRHJ5yOjy1RkNhlQydjn7097uUwxNNvw877O4YRr6xKQbHwlshJGtR0qSrVDcxr+8S5KE9znVWGy6wyCRkE8GtkTuvlqRe0n/JHD/+YjadQHjIjQDjnEUZh3FAzN/MMXh8KmlA5A3cE1x6NQQ/2Rm561vwgSVFx9EhzNXnMDZT51rfS5x5DyNC5gs/rp0Hhn7cZs2hiKJ5XplkrPoh2hzN3WYoaeJ7OjF/UOC7dVnGD7Fy/uD6zEwIjx4+/9SyNAm4DTis3Oa/LSYAqeZuyOmF1Ez1e98SY6K8+dEGu+2PCnYqPys3H796+mfLnUgoT+o+KN/RgP9RNmDlne1esvFxdJorDkxZY//WVaKxMVWDlId+TtU/7zVvFi4IuOyerHdw1A3Gu6sVK8iiWYUxZnu00sQTNeHVC+5P9yRTUjSj6pFfp+eX6u0Zg1Mngrc6cemdzt9RI2UGRlg3/G2qEqxEXDAtuuTeM9DqkM96MJiznLbdfP1miZogWF9jl8QXwdD5vqnEgUfvHNlgnY73ntO/kozYGuc2aqi0AaBmKFyWIKBIsj7bjguNHe0bVxyGbYTInKs2AQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
