travis:
  secure:
    BINSTAR_TOKEN: TNOb1QwkM8nq0BuvrJeeZ8IdhNc1+MWFGgTONikFuhnIaiJ/71sEz2EDYMGLaBsj3WP0siRAuPtL0gjfNSz76Lom4q0B/RabgJfyDy8Dw/YaDL3f4e/ztK5MnLmdDbEcfU8fN7rdwgCVHL1+kXTJNIUsn6zx47vq/ON7HcMchb+EX7iwPKM4kVnPpHqvIFcmpslXsQuL9vREvbRAsQqAWB2cVxuSFgX8yc0k4z+dlsqf4qLiBy89q6zx6N9qedg5Ia06kfK731u3e27zwaLNUwknvms3cn8dnVmuuDj9Xo4UfgB+T0vgxfPEMXt2glaMvN/9GI65FmP2IL431LqJJRR/41Dls5XImqaZ/0NPMUMLsnaBYeD95RXU/ntO9abOPXeyZcZFw2jTRX5UwWqI7Wsqbp7CmeXM57xLnOzRw9bBdfTyvi3vOhrtG+ppBGInYQL5fGYNeyyS3aIMjGsD/WEvBRjFzLARvDlfWq9Qgm8DvbB4oPGBslbNkt1NfDHEBlNewugEn5pu98Za2UeGKQfAI0MZ8K4hJuan6tUoINeKGb3eynFL3sj+MZT5mtjd+Qh5Q511y8GC235G0wE8yyKJph5R+gIybssnX/8I8UEoAivYbbIYfCBzO3vHaPltod/XlNWTwb54pP1bHfWPsZPuIeN7EYZ5+h1ybW0kpNA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
